import jsPDF from "jspdf"

const DR_LABELS = ["No DR", "Mild", "Moderate", "Severe", "Proliferative DR"]

const RECOMMENDATIONS = {
  "No DR": "No signs of diabetic retinopathy detected. Continue regular annual screening.",
  Mild: "Mild non-proliferative diabetic retinopathy detected. Follow up with your eye care provider within 6-12 months.",
  Moderate:
    "Moderate non-proliferative diabetic retinopathy detected. Follow up with your eye care provider within 3-6 months.",
  Severe:
    "Severe non-proliferative diabetic retinopathy detected. Follow up with your eye care provider within 1-3 months.",
  "Proliferative DR":
    "Proliferative diabetic retinopathy detected. Urgent referral to an ophthalmologist is recommended.",
}

// confidence keys come back from the backend as stringified class indices ("0".."4")
function normalizedConfidenceEntries(confidence) {
  if (!confidence || typeof confidence !== "object") return []
  return Object.entries(confidence).map(([key, score]) => {
    const idx = Number(key)
    const label = Number.isInteger(idx) && DR_LABELS[idx] ? DR_LABELS[idx] : key
    return [label, score]
  })
}

export function generateScanReportPDF({ patientName, patientEmail, fileName, date, imageDataUrl, result }) {
  const doc = new jsPDF()
  const grade = result?.class || result?.grade_label || "Unknown"

  doc.setFontSize(18)
  doc.text("Diabetic Retinopathy Detection Report", 14, 20)

  doc.setFontSize(10)
  doc.setTextColor(120)
  doc.text(`Report generated: ${new Date().toLocaleString()}`, 14, 27)

  doc.setDrawColor(210)
  doc.line(14, 31, 196, 31)

  doc.setFontSize(11)
  doc.setTextColor(0)
  let y = 40
  doc.text(`Patient: ${patientName || "N/A"}`, 14, y)
  y += 6
  doc.text(`Email: ${patientEmail || "N/A"}`, 14, y)
  y += 6
  doc.text(`Scan file: ${fileName || "N/A"}`, 14, y)
  y += 6
  doc.text(`Scan date: ${date ? new Date(date).toLocaleString() : new Date().toLocaleString()}`, 14, y)

  const imageTop = y + 10
  const textX = 84

  if (imageDataUrl) {
    try {
      doc.addImage(imageDataUrl, "JPEG", 14, imageTop, 60, 60)
    } catch (e) {
      console.error("Failed to embed image in PDF:", e)
    }
  }

  let ty = imageTop
  doc.setFontSize(13)
  doc.text("Diagnosis:", textX, ty)
  ty += 8
  doc.setFontSize(16)
  doc.setTextColor(180, 30, 30)
  doc.text(grade, textX, ty)
  doc.setTextColor(0)
  ty += 10

  const confidenceEntries = normalizedConfidenceEntries(result?.confidence)
  if (confidenceEntries.length > 0) {
    doc.setFontSize(10)
    doc.text("Confidence scores:", textX, ty)
    ty += 6
    confidenceEntries.forEach(([label, score]) => {
      doc.text(`${label}: ${(score * 100).toFixed(1)}%`, textX, ty)
      ty += 6
    })
  }

  let bottomY = Math.max(imageTop + 65, ty + 8)
  doc.setDrawColor(210)
  doc.line(14, bottomY, 196, bottomY)
  bottomY += 8

  doc.setFontSize(12)
  doc.setTextColor(0)
  doc.text("Recommendation:", 14, bottomY)
  bottomY += 7
  doc.setFontSize(10)
  const recText = RECOMMENDATIONS[grade] || "Please consult with your healthcare provider for interpretation of these results."
  const wrapped = doc.splitTextToSize(recText, 182)
  doc.text(wrapped, 14, bottomY)

  doc.setFontSize(8)
  doc.setTextColor(150)
  doc.text(
    doc.splitTextToSize(
      "Disclaimer: This report is generated by an AI-based screening tool and is for informational purposes only. It is not a substitute for professional medical diagnosis. Please consult a qualified ophthalmologist.",
      182,
    ),
    14,
    280,
  )

  const safeName = (fileName || "scan").replace(/\.[^/.]+$/, "").replace(/[^a-z0-9_-]/gi, "_")
  doc.save(`DR-Report-${safeName}.pdf`)
}
