import jsPDF from "jspdf"

const RECOMMENDATIONS = {
  "No DR": "No signs of diabetic retinopathy detected. Continue regular annual screening.",
  Mild: "Mild non-proliferative diabetic retinopathy detected. Follow up with your eye care provider within 6-12 months.",
  Moderate:
    "Moderate non-proliferative diabetic retinopathy detected. Follow up with your eye care provider within 3-6 months.",
  Severe:
    "Severe non-proliferative diabetic retinopathy detected. Follow up with your eye care provider within 1-3 months.",
  "Proliferative DR":
    "Proliferative diabetic retinopathy detected. Urgent referral to an ophthalmologist is recommended.",
}

// Actionable follow-up timeframe, shown as its own field instead of a raw
// model confidence percentage (which patients can misread as a certainty score).
const FOLLOWUP_TIMEFRAMES = {
  "No DR": "Annual screening",
  Mild: "6-12 months",
  Moderate: "3-6 months",
  Severe: "1-3 months",
  "Proliferative DR": "Urgent - as soon as possible",
}

export function generateScanReportPDF({
  patientName,
  patientAge,
  gender,
  diabetesType,
  diagnosisYear,
  phone,
  fileName,
  date,
  imageDataUrl,
  result,
}) {
  const doc = new jsPDF()
  const grade = result?.class || result?.grade_label || "Unknown"

  doc.setFontSize(18)
  doc.text("Diabetic Retinopathy Detection Report", 14, 20)

  doc.setFontSize(10)
  doc.setTextColor(120)
  doc.text(`Report generated: ${new Date().toLocaleString()}`, 14, 27)

  doc.setDrawColor(210)
  doc.line(14, 31, 196, 31)

  doc.setFontSize(11)
  doc.setTextColor(0)
  let y = 40
  doc.text(`Patient: ${patientName || "N/A"}`, 14, y)
  y += 6
  doc.text(`Age: ${patientAge || "N/A"}${gender ? `   |   Gender: ${gender}` : ""}`, 14, y)
  y += 6
  if (diabetesType) {
    doc.text(`Diabetes Type: ${diabetesType}${diagnosisYear ? ` (diagnosed ${diagnosisYear})` : ""}`, 14, y)
    y += 6
  }
  if (phone) {
    doc.text(`Phone: ${phone}`, 14, y)
    y += 6
  }
  doc.text(`Scan file: ${fileName || "N/A"}`, 14, y)
  y += 6
  doc.text(`Scan date: ${date ? new Date(date).toLocaleString() : new Date().toLocaleString()}`, 14, y)

  const imageTop = y + 10
  const textX = 84

  if (imageDataUrl) {
    try {
      doc.addImage(imageDataUrl, "JPEG", 14, imageTop, 60, 60)
    } catch (e) {
      console.error("Failed to embed image in PDF:", e)
    }
  }

  let ty = imageTop
  doc.setFontSize(13)
  doc.text("Diagnosis:", textX, ty)
  ty += 8
  doc.setFontSize(16)
  doc.setTextColor(180, 30, 30)
  doc.text(grade, textX, ty)
  doc.setTextColor(0)
  ty += 10

  doc.setFontSize(11)
  doc.text("Follow-up recommended by:", textX, ty)
  ty += 6
  doc.setFontSize(13)
  doc.setTextColor(180, 30, 30)
  doc.text(FOLLOWUP_TIMEFRAMES[grade] || "Consult your eye care provider", textX, ty)
  doc.setTextColor(0)
  ty += 10

  let bottomY = Math.max(imageTop + 65, ty + 8)
  doc.setDrawColor(210)
  doc.line(14, bottomY, 196, bottomY)
  bottomY += 8

  doc.setFontSize(12)
  doc.setTextColor(0)
  doc.text("Recommendation:", 14, bottomY)
  bottomY += 7
  doc.setFontSize(10)
  const recText = RECOMMENDATIONS[grade] || "Please consult with your healthcare provider for interpretation of these results."
  const wrapped = doc.splitTextToSize(recText, 182)
  doc.text(wrapped, 14, bottomY)

  doc.setFontSize(8)
  doc.setTextColor(150)
  doc.text(
    doc.splitTextToSize(
      "Disclaimer: This report is generated by an AI-based screening tool and is for informational purposes only. It is not a substitute for professional medical diagnosis. Please consult a qualified ophthalmologist.",
      182,
    ),
    14,
    280,
  )

  const safeName = (fileName || "scan").replace(/\.[^/.]+$/, "").replace(/[^a-z0-9_-]/gi, "_")
  doc.save(`DR-Report-${safeName}.pdf`)
}
